version: "3.9"

services:
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keywhale
    volumes:
      - ../backend/.mysql:/var/lib/mysql
  web:
    image: braiscabo/tfg:2d0bfb8e72f2b6f900ce1f10fbd3d35b50eb8cbd
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/keywhale
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
    ports:
      - 8443:8443