name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name : Hola
              run: |
                ls > directory_contents.txt
                cat directory_contents.txt
            - name: Create settings file
              run : ./h.sh
            - name: Mostrar contenido de settings.xml
              run: |
                  # Verifica si el archivo settings.xml existe antes de imprimirlo
                  if [ -f ~/.m2/settings.xml ]; then
                    cat ~/.m2/settings.xml
                  else
                    echo "El archivo settings.xml no existe en la ruta ~/.m2/"
                  fi