name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        
jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - name: Run tests
              run: mvn -f Backend/pom.xml test
