name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - uses: browser-actions/setup-chrome@latest
            - run: chrome --version
            - name: 'Create env file'
              run: |
                    echo "ImageName=${{ secrets.DOCKERHUB_IMAGE }}" > .env
                    echo "ImageTag=${{github.sha}}" > .env
            - name: Setup docker compose
              run: docker-compose up
            - name: Run tests
              run: mvn -f Backend/pom.xml test
            - name: Install Okteto CLI
              run: curl https://get.okteto.com -sSfL | sh
            - name: Login into Okteto
              run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
            - name: Deploy to Okteto
              run: okteto deploy --var ImageName=${{ secrets.DOCKERHUB_IMAGE }} --var ImageTag=${{ github.sha }}