name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        
jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - name: Run tests
              run: mvn -f Backend/pom.xml test
            - name: Login to docker
              run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            - name: Build the docker image
              run:  docker build -f Docker/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/tfg .
            - name: Push the docker image
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tfg
            - name: Install Okteto CLI
              run: curl https:</get.okteto.com -sSfL | sh
            - name: Login into Okteto
              run: okteto context use https:</cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
            - name: Deploy to Okteto
              run: okteto deploy --wait