name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
        
jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - name: Update .env
              run: |
                  echo "ImageName=${{ secrets.DOCKER_IMAGE_NAME }}" >> .env
                  echo "ImageTag=${{ github.sha }}" >> .env
            - name: Install Okteto CLI
              run: curl https://get.okteto.com -sSfL | sh
            - name: Login into Okteto
              run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
            - name: Deploy to Okteto
              run: okteto deploy --wait