name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
            ubuntu-latest
        steps:
            ## Step 1: Configuration
            - uses: actions/checkout@v3
            - uses: s4u/maven-settings-action@v2.8.0
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - uses: browser-actions/setup-chrome@latest
            - run: chrome --version
            - name: Give execution permissions to create settings script
              run: chmod +x createSettings.sh
            - name: Create settings file
              run: ./createSettings.sh ${{secrets.GH_USERNAME}} ${{secrets.GH_TOKEN}} ~/.m2/settings.xml
            - name: Copy maven settings to docker
              run: cp ~/.m2/settings.xml Docker/settings.xml
            - name: 'Create env file'
              run: |
                echo "ImageName=${{ secrets.DOCKERHUB_IMAGE }}" > .env
                echo "ImageTag=${{ github.sha }}" >> .env
                
            ## Step 2: Docker Login and Image Build
            - name: Login to docker
              run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            - name: Build the docker image
              run: docker build -f Docker/Dockerfile -t ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }} .

            
            - name: Push the docker image
              run: docker push ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }}

    deploy:
      needs: publish
      runs-on:
        ubuntu-latest
      steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'

        - name: Deploy to Google Cloud Run
          run: |
            gcloud run deploy corregia \
            --image ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }} \
            --region us-central1 \
            --allow-unauthenticated \
            --platform managed \
            --set-env-vars SPRING_DATASOURCE_URL=jdbc:mysql://34.28.247.197:3306/keywhale \
            --set-env-vars SPRING_DATASOURCE_USERNAME=root \
            --set-env-vars SPRING_DATASOURCE_PASSWORD=${{ secrets.GCP_DB_PASSWORD }} \
            --set-env-vars SPRING_JPA_HIBERNATE_DDL-AUTO=update