name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            ## Step 1: Configuration
            - uses: actions/checkout@v3
            - uses: s4u/maven-settings-action@v2.8.0
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - uses: browser-actions/setup-chrome@latest
            - run: chrome --version
            - name: Give execution permitions to create settings script
              run: chmod +x createSettings.sh
            - name: Create settings file
              run : ./createSettings.sh ${{secrets.GH_USERNAME}} ${{secrets.GH_TOKEN}} ~/.m2/settings.xml
            - name : Copy maven settings to docker
              run : cp ~/.m2/settings.xml Docker/settings.xml
            - name: 'Create env file'
              run: |
                echo "ImageName=${{ secrets.DOCKERHUB_IMAGE }}" > .env
                echo "ImageTag=${{ github.sha }}" >> .env
                
            ## Step 2: Docker Login and Image Build
            - name: Login to docker
              run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            - name: Build the docker image
              run:  docker build -f Docker/Dockerfile -t ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }} .

            ## Step 3: Image Execution and Wait to Image Start
            - name: Setup docker compose
              run: docker-compose up -d
            - name : Give permitions to wait containers start script
              run : chmod +x waitContainer.sh
            - name: Wait for containers to start
              run: ./waitContainer.sh

              ## Step 4: Test execution
            - name: Run tests
              run: mvn -f Backend/pom.xml test

              ## Step 5: End Image Execution and Push image to Docker Hub
            - name: Stop docker compose
              run: docker-compose down
            - name: Push the docker image
              run: docker push ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }}

              ## Step 6: Configure Okteto and deploy application
            - name: Install Okteto CLI
              run: curl https://get.okteto.com -sSfL | sh
            - name: Login into Okteto
              run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
            - name: Deploy to Okteto
              run: okteto deploy --var ImageName=${{ secrets.DOCKERHUB_IMAGE }} --var ImageTag=${{ github.sha }}
