name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: s4u/maven-settings-action@v2.8.0
            - name: Dar permisos de ejecución al script
              run: chmod +x createSettings.sh
            - name: Create settings file
              run : ./createSettings.sh ${{secrets.GH_USERNAME}} ${{secrets.GH_TOKEN}} ~/.m2/settings.xml
            - name : Copy maven settings to docker
              run : cp ~/.m2/settings.xml Docker/settings.xml
            - name: Mostrar contenido de settings.xml
              run: |
                  # Verifica si el archivo settings.xml existe antes de imprimirlo
                  if [ -f Docker/settings.xml ]; then
                    cat Docker/settings.xml
                  else
                    echo "El archivo settings.xml no existe en la ruta ~/.m2/"
                  fi