name: CICD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    publish:
        runs-on:
             ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: s4u/maven-settings-action@v2.8.0
            - name: Set up JDK 20
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '20'
            - uses: browser-actions/setup-chrome@latest
            - run: chrome --version
            - name: Give execution permitions to create settings script
              run: chmod +x createSettings.sh
            - name: Create settings file
              run : ./createSettings.sh ${{secrets.GH_USERNAME}} ${{secrets.GH_TOKEN}} ~/.m2/settings.xml
            - name : Copy maven settings to docker
              run : cp ~/.m2/settings.xml Docker/settings.xml
            - name: 'Create env file'
              run: |
                echo "ImageName=${{ secrets.DOCKERHUB_IMAGE }}" > .env
                echo "ImageTag=${{ github.sha }}" >> .env
            - name: Login to docker
              run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            - name: Build the docker image
              run:  docker build -f Docker/Dockerfile -t ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }} .
            - name: Stop docker compose
              run: docker-compose down
            - name: Push the docker image
              run: docker push ${{ secrets.DOCKERHUB_IMAGE }}:${{ github.sha }}
            - name: Install Gitpod CLI
              run: curl -L https://github.com/gitpod-io/gitpod/releases/download/v0.10.0/gitpod-cli-linux > /usr/local/bin/gitpod && chmod +x /usr/local/bin/gitpod
            - name: Login to Gitpod
              run: gitpod login --auth-token ${{ secrets.GITPOD_TOKEN }}
            - name: Deploy to Gitpod
              run: |
                gitpod start workspace \
                --repo https://github.com/${{ github.repository }} \
                --branch ${{ github.ref }} \
                --command "docker-compose up -d"